apiVersion: v1
kind: ReplicationController
metadata:
  name: helloworld-controller
spec:
  replicas: 2
  selector:
    app: docker-get-started
  template:
    metadata:
      labels:
        app: docker-get-started
    spec:
      containers:
      - name: docker-get-started
        image: amitvashist7/apache-ex4
        ports:
        - name: http-port
          containerPort: 8081
